version: "3.9"
services:
  web:
    image: php:7.4-apache
    ports:
      - "5000:80"
    volumes:
      - "./html:/var/www/html"
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin:apache
    ports:
      - "5050:80"
    environment:
      # - PMA_ARBITRARY: "1"
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - database
